gantsign/ansible-role-visual-studio-code-extensions

.travis.yml, molecule.yml
Keeping up with the latest changes.
=> Updated Molecule to 1.16

meta/main.yml
Ansible Galaxy is fussy about the values.
=> Fixed MacOSX metadata

README.md, defaults/main.yml, molecule.yml, tasks/main.yml, tests/test.yml
Now handles SUSE `users` group.
=> Made role SUSE compatible

tasks/main.yml
Let's assume Visual Studio Code and its dependencies have been installed correctly.
=> Removed unnecessary dependency install

README.md, tests/test.yml, tests/test_role.py
It's now an official Microsoft project.
=> Fixed Python extension ID in test

tests/test.yml
Replaced with alternate extension.
=> Fix for discontinued spell check extension

README.md, defaults/main.yml, tasks/main.yml
The previous approach only handled some specific cases.
=> Improved assignment of default group for dirs

.travis.yml, molecule/default/molecule.yml, molecule/opensuse/Dockerfile.j2, molecule/opensuse/INSTALL.rst, molecule/opensuse/molecule.yml
In preparation for supporting additional distributions.
=> Split distributions into separate Travis CI builds

.travis.yml, README.md, meta/main.yml, molecule/default/playbook.yml, molecule/fedora/Dockerfile.j2, molecule/fedora/INSTALL.rst, molecule/fedora/molecule.yml, tasks/main.yml
Added to the tested distributions.
=> Added support for Fedora 27

molecule/centos/molecule.yml, molecule/fedora/molecule.yml, molecule/opensuse/molecule.yml
Removed unnecessary trailing slash.
=> Fixed location of Molecule tests

.travis.yml, README.md, meta/main.yml, molecule/ubuntu-min/Dockerfile.j2, molecule/ubuntu-min/INSTALL.rst, molecule/ubuntu-min/molecule.yml
The latests LTS release of Ubuntu.
=> Added support for Ubuntu Bionic

README.md, meta/main.yml, molecule/fedora/molecule.yml
Keeping up with the latest release.
=> Upgraded Fedora version to 28

README.md, meta/main.yml, molecule/default/playbook.yml, molecule/opensuse/molecule.yml
Keeping up with the latest release.
=> Upgraded openSUSE version to 15.0

.travis.yml, library/visual_studio_code_extensions.py, molecule/default/playbook.yml, molecule/python3/Dockerfile.j2, molecule/python3/INSTALL.rst, molecule/python3/molecule.yml, tasks/main.yml, vars/pkg-mgr/apt.yml, vars/pkg-mgr/default.yml, vars/pkg-mgr/dnf.yml
If an extension is already installed it will now be upgraded.
=> Added support for upgrading extensions

README.md, defaults/main.yml, library/visual_studio_code_extensions.py, molecule/default/playbook.yml, molecule/default/tests/test_role.py, tasks/main.yml, vars/main.yml
For those who want to help test the latest features.
Enhancement: resolves #65
=> Added support for VS Code Insiders builds

library/visual_studio_code_extensions.py
=> Reformatted Python code

vars/pkg-mgr/homebrew.yml
Given I don't have a Mac and there are no tests for macOS, we're dependent on the community for fixes, so use at your own risk.
=> Added undocumented macOS support

library/visual_studio_code_extensions.py, molecule/default/converge.yml
=> Updated test dependencies

README.md, library/visual_studio_code_extensions.py, tasks/main.yml, vars/main.yml
=> Add OSS support

README.md, defaults/main.yml, library/visual_studio_code_extensions.py, tasks/main.yml, vars/main.yml
=> Added VS Code OSS support

molecule/fedora/molecule.yml, molecule/opensuse/molecule.yml, molecule/rocky/molecule.yml, molecule/ubuntu-min/molecule.yml
=> Removed unused test dockerfile config

.github/workflows/ci.yml, README.md, meta/main.yml, molecule/default/molecule.yml
The latests LTS release of Ubuntu.
=> Increased upper Ubuntu test version to Jammy

.ansible-lint, .yamllint, meta/main.yml, molecule/opensuse/collections.yml, molecule/opensuse/converge.yml, molecule/opensuse/molecule.yml, tasks/main.yml
In preparation for Molecule upgrade.
=> Fixed Ansible Lint warnings

defaults/main.yml, molecule/default/converge.yml, molecule/opensuse/converge.yml, tasks/main.yml, vars/main.yml, vars/pkg-mgr/apt.yml, vars/pkg-mgr/default.yml, vars/pkg-mgr/dnf.yml, vars/pkg-mgr/homebrew.yml, vars/pkg-mgr/zypper.yml
For improved VS Code editing support.
=> Added Ansible modelines

molecule/default/converge.yml, molecule/default/tests/test_role.py, molecule/opensuse/converge.yml
The Editor Config extension ID has changed case for the insiders build.
=> Fixed tests
